version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     - NODE_ENV=development
  database:
    image: postgres:15-alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - backed-database:/var/lib/postgresql/data
      - ./src/util/test/db-creation.sql:/docker-entrypoint-initdb.d/db-creation.sql
    environment:
      POSTGRES_USER: sct_admin
      POSTGRES_PASSWORD: pAssw0rd
volumes:
  backed-database:
